Repository materialsproject/fireworks, pull requests merged in 2023-08, with the labels that each got.

#505 Fix `webgui` KeyError
  fireworks/flask_site/util.py
Labels: webgui, fix

#507 Fix ambiguous var names
  fireworks/core/firework.py
  fireworks/core/launchpad.py
  fireworks/core/rocket.py
  fireworks/core/tests/test_launchpad.py
  fireworks/features/fw_report.py
  fireworks/features/introspect.py
  fireworks/flask_site/helpers.py
  fireworks/queue/queue_adapter.py
  fireworks/scripts/lpad_run.py
  fireworks/scripts/tests/test_lpad_run.py
  fireworks/scripts/tests/test_qlaunch_run.py
  fireworks/scripts/tests/test_rlaunch_run.py
  fireworks/tests/master_tests.py
  fireworks/tests/mongo_tests.py
  fireworks/user_objects/firetasks/tests/test_dataflow_tasks.py
  fireworks/user_objects/firetasks/tests/test_filepad_tasks.py
  fireworks/user_objects/queue_adapters/common_adapter.py
  fireworks/utilities/dagflow.py
  fireworks/utilities/tests/test_filepad.py
  fireworks/utilities/visualize.py
Labels: linting

#503 [BUG FIX] remove `_id` from `archived_launches`
  fireworks/flask_site/app.py
Labels: question

#509 Bump minimum Python version to 3.8
  .circleci/config.yml
  docs/_sources/installation.rst.txt
  docs_rst/installation.rst
  setup.py
Labels: pkg
