Repository materialsproject/fireworks, pull requests merged in 2024-04, with the labels that each got.

#518 Logging in rocket.py and launch_rocket.py
  docs_rst/config_tutorial.rst
  fireworks/core/rocket.py
Labels: fix

#523 Fix `lpad.delete_fws` if `fw_id` not found
  fireworks/core/launchpad.py
Labels: fix, lpad

#525 Migrate CI tests from CircleCI to GitHub Actions
  .circleci/config.yml
  .github/workflows/test.yml
  requirements.txt
  setup.py
Labels: dependencies, ci

#529 `ruff` fixes
  fireworks/core/firework.py
  fireworks/core/fworker.py
  fireworks/core/launchpad.py
  fireworks/core/rocket.py
  fireworks/core/rocket_launcher.py
  fireworks/features/fw_report.py
  fireworks/features/multi_launcher.py
  fireworks/features/stats.py
  fireworks/flask_site/app.py
  fireworks/queue/queue_launcher.py
  fireworks/scripts/lpad_run.py
  fireworks/user_objects/firetasks/script_task.py
  fireworks/user_objects/queue_adapters/common_adapter.py
  fireworks/utilities/filepad.py
  fireworks/utilities/fw_utilities.py
Labels: linting
